#!/bin/bash

# build script for descent

# as soon as possible, convert to grunt

pwd

TASK="$1"

if [ "$TASK" == "" ] ; then
  TASK="all"
fi

if [ "$TASK" == "clean" ] ; then
  CLEAN=1
  BUILD=0
  TEST=0
elif [ "$TASK" == "build" ] ; then
  CLEAN=1
  BUILD=1
  TEST=0
elif [ "$TASK" == "test" ] ; then
  CLEAN=0
  BUILD=0
  TEST=1
elif [ "$TASK" == "all" ] ; then
  CLEAN=1
  BUILD=1
  TEST=1
fi

if [ "$CLEAN" == 1 ] ; then
  echo "deleting build dir"
  echo "> rf -rf dst/"
  rm -rf dst/

  echo "deleting test build dir"
  echo "> rf -rf test/dst/"
  rm -rf test/dst/
fi

if [ "$BUILD" == 1 ] ; then
  echo "creating build dir"
  echo "> mkdir dst"
  mkdir dst

  echo "building coffeescripts"
  echo "> coffee -c -o dst/ coffee/"
  coffee -c -o dst/ coffee/

  echo "building parser"
  echo "> jison -o dst/parser.js jison/descent.js"
  jison -o dst/parser.js jison/descent.jison

  echo "patching parser"
  echo "> patch dst/parser.js < loadLexer.patch"
  patch dst/parser.js < loadLexer.patch
fi

if [ "$TEST" == 1 ] ; then
  echo "building lexer tests"
  echo "> coffee -c -o test/dst/ test/coffee/"
  coffee -c -o test/dst/ test/coffee/

  echo "running lexer tests"
  echo "> node test/dst/lexer_test.js"
  node test/dst/lexer_test.js
  echo "running parser tests"
  echo "> node test/dst/parser_test.js"
  node test/dst/parser_test.js
fi
