#!/bin/bash

# build script for descent

# as soon as possible, convert to grunt

pwd

if [ "$1" == "clean" ] ; then
  echo "deleting build dir"
  echo "> rf -rf dst/"
  rm -rf dst/

  echo "deleting test build dir"
  echo "> rf -rf test/dst/"
  rm -rf test/dst/
elif [ "$1" == "test" ] ; then
  echo "building lexer tests"
  echo "> coffee -c -o test/dst/ test/coffee/"
  coffee -c -o test/dst/ test/coffee/

  echo "running lexer tests"
  echo "> node test/dst/lexer_test.js"
  node test/dst/lexer_test.js
else
  echo "creating build dir"
  echo "> mkdir dst"
  mkdir dst

  echo "building coffeescripts"
  echo "> coffee -c -o dst/ coffee/"
  coffee -c -o dst/ coffee/

  echo "building parser"
  echo "> jison -o dst/parser.js jison/descent.js"
  jison -o dst/parser.js jison/descent.jison

  echo "patching parser"
  echo "> patch dst/parser.js < loadLexer.patch"
  patch dst/parser.js < loadLexer.patch
fi
