public class SwitchGenerate
{
    {
        if ( favoriteLanguage == 'Ruby' )
        {
            System.log('Ruby is great');
        }
        else if ( favoriteLanguage == 'JavaScript' )
        {
            System.log('Love making web apps');
        }
        else if ( favoriteLanguage == 'Descent' )
        {
            System.log('Of course');
        }
        else
        {
            System.log('I don\'t know that one');
        }
    }
}
