public class SwitchGenerate
{
    public void check()
    {
        if ( favoriteLanguage == 'Ruby' )
        {
            System.debug('Ruby is great');
        }
        else if ( favoriteLanguage == 'JavaScript' )
        {
            System.debug('Love making web apps');
        }
        else if ( favoriteLanguage == 'Descent' )
        {
            System.debug('Of course');
        }
        else
        {
            System.debug('I don\'t know that one');
        }
    }
}
