Postfix
  mood = greatlyImproved if singing
  goForPicnic() unless raining

Blocks
  if happy and knowsIt
    clapHands()
    chaChaCha()
  else
    showIt()
  unless grounded
    playHookey()

Assignment
  date = if friday then sue else jill

SwitchGenerate
  switch favoriteLanguage
  case 'Ruby'
    System.log 'Ruby is great'
  case 'JavaScript'
    System.log 'Love making web apps'
  case 'Descent'
    System.log 'Of course'
  default
    System.log "I don't know that one"
