public class Exist
{
    public basicCheck()
    {
        Boolean solipsism;
        Integer speed;
        Object footprints;

        if ( mind != null && !( world != null ) )
        {
            solipsism = true;
        }

        speed = 0;
        if ( speed == null )
        {
            speed = 15;
        }

        if ( yeti != null )
        {
            footprints = yeti;
        }
        else
        {
            footprints = "bear";
        }
    }

    public accessorVariant()
    {
        Winner ref = lottery.drawWinner();
        if ( ref != null )
        {
            if ( ref.address != null )
            {
                zip = ref.address.zipcode;
            }
        }
    }
}
