public class Exist
{
    String mind = 'blown';
    String world;
    String yeti;
    Lottery lottery = new Lottery();

    public basicCheck()
    {
        Boolean solipsism;
        Integer speed;
        String footprints;

        if ( mind != null && !( world != null ) )
        {
            solipsism = true;
        }

        speed = 0;
        if ( speed == null )
        {
            speed = 15;
        }

        if ( yeti != null )
        {
            footprints = yeti;
        }
        else
        {
            footprints = "bear";
        }
    }

    public accessorVariant()
    {
        Winner ref = lottery.drawWinner();
        if ( ref != null )
        {
            if ( ref.address != null )
            {
                zip = ref.address.zipcode;
            }
        }
    }
    public class Lottery
    {
        public Person drawWinner()
        {
            return new Person();
        }
    }

    public class Person
    {
        Address address;
    }

    public class Address
    {
        String zipcode;
    }
}
