// Generated by CoffeeScript 1.4.0
(function() {

  Aliases(function() {
    tautology(function() {
      if (1 === 1 && 1 !== 2) {
        if (1 === 2 || 1 !== 2) {
          if (true === true && true === true) {
            if (false === false && false === false) {
              return print('whew');
            }
          }
        }
      }
    });
    return confusing(function() {
      if (!!false) {
        print('how did i get here?');
      }
      if (!!false) {
        return print('same question');
      }
    });
  });

  Example(function() {
    var answer, band, car, ignition, limit, volume;
    ignition = false;
    volume = 11;
    band = 'Peter, Paul, and Mary';
    answer = true;
    winner;

    car = Car;
    limit = 60;
    launch(function() {});
    letTheWildRumpusBegin(function() {});
    accelerate(function() {});
    pick(function() {
      return 42;
    });
    useful(function(name) {
      return this.name = name;
    });
    doIt(function() {
      var winner;
      if (ignition === true) {
        launch();
      }
      if (band !== 'SpinalTap') {
        volume = 10;
      }
      if (answer !== false) {
        letTheWildRumpusBegin();
      }
      if (car.speed < limit) {
        accelerate();
      }
      if (pick === 47 || pick === 92 || pick === 13) {
        winner = true;
      }
      return print("My name is " + this.name);
    });
    SpinalTap(function() {});
    return Car(function() {
      return function() {
        return this.speed = 15;
      };
    });
  });

}).call(this);
