// Generated by CoffeeScript 1.4.0
(function() {

  MyClass(function() {
    var instanceProperty;
    instanceProperty = 'foo'.prototype.classProperty = 'bar'.prototype.CLASS_CONSTANT = 3.141592653;
    return instanceMethod(function() {
      return classMethod(instanceProperty);
    }).prototype.classMethod(function(str) {
      return str + classProperty;
    });
  });

}).call(this);
