// Generated by CoffeeScript 1.4.0
(function() {

  Postfix(function() {
    var greatlyImproved;
    greatlyImproved = 'sunshine and rainbows';
    singing(function() {
      return true;
    });
    raining(function() {
      return false;
    });
    goForPicnic(function() {
      return print('lovely day');
    });
    return check(function() {
      var mood;
      if (singing) {
        mood = greatlyImproved;
      }
      if (!raining) {
        return goForPicnic();
      }
    });
  });

  Blocks(function() {
    var grounded, happy, knowsIt;
    happy = true;
    knowsIt = true;
    grounded = false;
    clapHands(function() {
      return print('*CLAP*');
    });
    chaChaCha(function() {
      return print('cha-cha-cha');
    });
    playHookey(function() {
      return print('going to arcade');
    });
    return check(function() {
      if (happy && knowsIt) {
        clapHands();
        chaChaCha();
      } else {
        showIt();
      }
      if (!grounded) {
        return playHookey();
      }
    });
  });

  Assignment(function() {
    var jill, sue;
    sue = 'hot';
    jill = 'not';
    friday(function() {
      return false;
    });
    return check(function() {
      var date;
      return date = friday ? sue : jill;
    });
  });

  SwitchGenerate(function() {
    var favoriteLanguage;
    favoriteLanguage = 'Sass';
    return check(function() {
      switch (favoriteLanguage) {
        case 'Ruby':
          return print('Ruby is great');
        case 'JavaScript':
        case 'ActionScript':
          return print('Love making web apps');
        case 'Descent':
          return print('Of course');
        default:
          return print("I don't know that one");
      }
    });
  });

}).call(this);
