// Generated by CoffeeScript 1.4.0
(function() {

  Foobar(function() {
    return someFunction(function() {
      var i;
      i = 5;
      i += Math.randInt(7);;

      return i;
    });
  });

}).call(this);
