// Generated by CoffeeScript 1.4.0
(function() {

  Basic(function() {
    eat(function(food) {
      return print("eating " + food);
    });
    menu(function(num, item) {
      return print("" + num + ".) " + item);
    });
    return doStuff(function() {
      var courses, dish, food, foods, i, _i, _j, _k, _len, _len1, _len2, _ref, _results;
      _ref = ['toast', 'cheese', 'wine'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        food = _ref[_i];
        eat(food);
      }
      courses = ['greens', 'caviar', 'truffles', 'roast', 'cake'];
      for (i = _j = 0, _len1 = courses.length; _j < _len1; i = ++_j) {
        dish = courses[i];
        menu(i + 1, dish);
      }
      foods = ['broccoli', 'spinach', 'chocolate'];
      _results = [];
      for (_k = 0, _len2 = foods.length; _k < _len2; _k++) {
        food = foods[_k];
        if (food !== 'chocolate') {
          _results.push(eat(food));
        }
      }
      return _results;
    });
  });

  Comprehensions(function() {
    doStuff(function() {
      var countdown, num;
      return countdown = (function() {
        var _i, _results;
        _results = [];
        for (num = _i = 10; _i >= 1; num = --_i) {
          _results.push(num);
        }
        return _results;
      })();
    });
    return maps(function() {
      var age, ages, child, yearsOld;
      yearsOld = {
        max: 10,
        ida: 9,
        tim: 11
      };
      return ages = (function() {
        var _results;
        _results = [];
        for (child in yearsOld) {
          age = yearsOld[child];
          _results.push("" + child + " is " + age);
        }
        return _results;
      })();
    });
  });

  WhileLoop(function() {
    var demand, studyingEconomics, supply;
    studyingEconomics = true;
    supply = 5;
    demand = 4;
    buy(function() {
      return --supply;
    });
    sell(function() {
      return --demand;
    });
    econ101(function() {
      var _results;
      if (this.studyingEconomics) {
        while (supply > demand) {
          buy();
        }
        _results = [];
        while (!(supply > demand)) {
          _results.push(sell());
        }
        return _results;
      }
    });
    nurseryRhyme(function() {
      var lyrics, num;
      num = 6;
      return lyrics = (function() {
        var _results;
        _results = [];
        while (num -= 1) {
          _results.push("" + num + " little monkeys, jumping on the bed.        One fell out and bumped his head.");
        }
        return _results;
      })();
    });
    return purgatory(function() {
      var _results;
      _results = [];
      while (true) {
        _results.push(econ101());
      }
      return _results;
    });
  });

}).call(this);
